CREATE TABLE  User (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL, 
    password VARCHAR(255) NOT NULL
);

CREATE TABLE Recipe (
    id VARCHAR(255) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    ingredientes VARCHAR(255) NOT NULL,
    description  VARCHAR(255) NOT NULL, 
    userId  VARCHAR(255) NOT NULL
);
